argocd:
  fullnameOverride: bootstrap-argocd
  configs:
    cm:
      users.anonymous.enabled: true
      statusbadge.enabled: true
      statusbadge.url: https://argocd.aidenharwood.uk/
      url: https://argocd.aidenharwood.uk
    rbac:
      policy.default: role:readonly
    params:
      server.insecure: true
  controller:
    metrics:
      enabled: true
metallb:
  enabled: false
local_path_provisioner:
  enabled: false
nginx_ingress_controller:
  enabled: false
cilium:
  enabled: false
lgtm:
  enabled: false
minio:
  enabled: false
tetragon:
  enabled: false