apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    helm:
      values: |
        configs:
          cm:
            accounts.guest: login
            url: https://argocd.aidenharwood.uk

            policy.default: role:readonly
            policy.overlay.csv: |
              g, guest, role:readonly
          secret:
            extra:
              # accounts.guest.password: {{ (htpasswd "guest" "guest" | splitList ":" | index 1) | trim }}
          params:
            server.insecure: true
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.2.5
    chart: argo-cd
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true